<?php

namespace AppBundle\Repository;

/**
 * CaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasesRepository extends \Doctrine\ORM\EntityRepository
{
}
