<?php

namespace AppBundle\Repository;

/**
 * CheatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheatRepository extends \Doctrine\ORM\EntityRepository
{
}
