<?php

namespace AppBundle\Repository;

/**
 * FinanceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
