<?php

namespace AppBundle\Repository;

/**
 * OutputRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutputRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
