<?php

namespace AppBundle\Repository;

/**
 * PaymenthistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymenthistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
