<?php

namespace AppBundle\Repository;

/**
 * ReferalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferalRepository extends \Doctrine\ORM\EntityRepository
{
}
