<?php

namespace AppBundle\Repository;

/**
 * ReferalhistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferalhistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
