# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.referalsystem:
        class: AppBundle\Util\ReferalSystem
        parameters: []
    app.usersystem:
        class: AppBundle\Util\UserSystem
        parameters: []
    app.financesystem:
        class: AppBundle\Util\FinanceSystem
        parameters: []
    app.winsystem:
        class: AppBundle\Util\WinSystem
        parameters: []
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
